Repository doctrine-extensions/DoctrineExtensions, pull requests merged in 2021-11, with the labels that each got.

#2272 Allow to install `doctrine/orm` 2.10
  CHANGELOG.md
  composer.json
  src/Loggable/LoggableListener.php
  src/Mapping/Event/Adapter/ODM.php
  src/Mapping/Event/Adapter/ORM.php
  src/Mapping/Event/AdapterInterface.php
  src/Mapping/MappedEventSubscriber.php
  src/Sluggable/Handler/InversedRelativeSlugHandler.php
  src/Sluggable/Handler/TreeSlugHandler.php
  src/Sortable/SortableListener.php
  src/Translatable/Document/Repository/TranslationRepository.php
  src/Translatable/Entity/Repository/TranslationRepository.php
  src/Translatable/TranslatableListener.php
  src/Tree/Entity/Repository/ClosureTreeRepository.php
  src/Tree/Entity/Repository/NestedTreeRepository.php
  src/Tree/Strategy/AbstractMaterializedPath.php
  src/Tree/Strategy/ORM/Closure.php
  src/Tree/Strategy/ORM/Nested.php
  src/Uploadable/UploadableListener.php
Labels: BC Break

#2287 Fix return value for `replaceRelative()` and `replaceInverseRelative()` at `Gedmo\Sluggable\Mapping\Event\Adapter\ODM`
  CHANGELOG.md
  src/Sluggable/Mapping/Event/Adapter/ODM.php
Labels: Bug

#2291 Fix value passed in the `--config` option to `fix-cs` Composer script
  CHANGELOG.md
  composer.json
Labels: Bug

#2297 Update status badges
  README.md
Labels: Documentation

#2313 Fix changelog for 3.3.0
  CHANGELOG.md
Labels: Documentation

#2315 [Loggable] Fix missinig support for `versioned` fields at `attribute-override` in XML mapping
  CHANGELOG.md
  src/Loggable/Mapping/Driver/Xml.php
Labels: Bug, Loggable

#2312 Fix `Gedmo\Mapping\Driver\Xml::_loadMappingFile()` behavior
  CHANGELOG.md
  src/Mapping/Driver/Xml.php
Labels: Bug

#2308 Use `Connection::executeStatement()` for "DELETE" statements
  CHANGELOG.md
  src/Tree/Entity/Repository/ClosureTreeRepository.php
  src/Tree/Strategy/ORM/Closure.php
Labels: Bug, Tree

#2314 [Tree] Fix `TreePathHash` implementation in XML driver
  CHANGELOG.md
  schemas/orm/doctrine-extensions-mapping-2-2.xsd
  src/Tree/Mapping/Driver/Xml.php
  tests/Gedmo/Mapping/Driver/Xml/Gedmo.Tests.Mapping.Fixture.Xml.MaterializedPathTree.dcm.xml
  tests/Gedmo/Mapping/Fixture/Xml/MaterializedPathTree.php
  tests/Gedmo/Mapping/Xml/MaterializedPathTreeMappingTest.php
Labels: Bug, Tree

#2322 [Translatable] Fix mixing attributes and annotations
  CHANGELOG.md
  src/Mapping/Driver/AttributeAnnotationReader.php
  src/Mapping/Driver/AttributeReader.php
  src/Mapping/ExtensionMetadataFactory.php
  src/Translatable/Mapping/Driver/Attribute.php
  tests/Gedmo/Translatable/AttributeEntityTranslationTableTest.php
  tests/Gedmo/Translatable/Fixture/Attribute/File.php
Labels: Bug, Translatable
