Repository doctrine-extensions/DoctrineExtensions, pull requests merged in 2023-08, with the labels that each got.

#2662 docs: improve test section of README.md
  README.md
Labels: Documentation

#2667 Update Symfony docs
  doc/symfony.md
Labels: Documentation

#2651 [Mapping] Fix inherited classes metadata collection
  CHANGELOG.md
  src/Mapping/ExtensionMetadataFactory.php
  tests/Gedmo/Mapping/Fixture/MappedSuperClass.php
  tests/Gedmo/Mapping/Fixture/SuperClassExtension.php
  tests/Gedmo/Mapping/MappingEventSubscriberTest.php
Labels: Bug

#2670 fix: if xml value is set, change value in class metadata
  CHANGELOG.md
  schemas/orm/doctrine-extensions-mapping-2-2.xsd
  src/References/Mapping/Driver/Xml.php
  tests/Gedmo/Mapping/Driver/Xml/Gedmo.Tests.Mapping.Fixture.Xml.References.dcm.xml
  tests/Gedmo/Mapping/Fixture/Xml/References.php
  tests/Gedmo/Mapping/Xml/ReferencesMappingTest.php
Labels: Bug, References
