Repository doctrine-extensions/DoctrineExtensions, pull requests merged in 2024-10, with the labels that each got.

#2880 Fix @note annotation error
  src/Loggable/Entity/MappedSuperclass/AbstractLogEntry.php
Labels: Bug, Loggable

#2881 Update README.md
  README.md
Labels: Documentation

#2888 fix: Casting issue due to MariaDB not included in inheritance schema anymore
  CHANGELOG.md
  src/Translatable/Query/TreeWalker/TranslationWalker.php
Labels: Bug
